class UnsupportedTypeException(Exception):
    ...

class MissingAttributeException(Exception):
    ...

class InvalidAttributeTypeException(Exception):
    ...

class CantFindTypeException(Exception):
    ...